# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 10:40
from __future__ import unicode_literals

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=encrypted_fields.fields.EncryptedCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=encrypted_fields.fields.EncryptedCharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='text',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
