# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170703_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=254),
        ),
    ]
