# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='SOME STRING', max_length=255, verbose_name='カテゴリ名'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
