# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170614_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='when',
            field=models.CharField(default='SOME STRING', max_length=255, verbose_name='時期'),
        ),
    ]
