# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(default='SOME STRING', max_length=200)),
                ('value', models.CharField(default='SOME STRING', max_length=200)),
                ('easy', models.IntegerField(default=0)),
                ('normal', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=200)),
                ('question1', models.CharField(max_length=200)),
                ('question2', models.CharField(max_length=200)),
                ('question3', models.CharField(max_length=200)),
            ],
        ),
    ]
