# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keijiban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='pk_label',
            field=models.IntegerField(null=True),
        ),
    ]
