# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='あなたの名前を入力してください', max_length=64, verbose_name='名前')),
                ('message', models.TextField(help_text='メッセージを入力してください', null=True, verbose_name='メッセージ')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='ご用件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
