# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='名前')),
                ('day', models.CharField(max_length=255, verbose_name='曜日')),
                ('time', models.CharField(max_length=255, verbose_name='時間')),
                ('sub', models.CharField(max_length=255, verbose_name='科目名')),
                ('when', models.CharField(max_length=255, verbose_name='時期')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='名前')),
                ('day', models.CharField(max_length=255, verbose_name='曜日')),
                ('time', models.CharField(max_length=255, verbose_name='時間')),
                ('sub', models.CharField(max_length=255, verbose_name='科目名')),
                ('when', models.CharField(max_length=255, verbose_name='時期')),
            ],
        ),
    ]
